[CHERRY-PICK] MdePkg/AArch64: fix AsmMacroLib signed value handling for MOV32/MOV64
MOV32 and MOV64, defined in AsmMacrolib.h, use a combination of movz and
movk instructions to fill a register with an immediate value. With each
instruction supplying 16 of the bits.

CLANGPDB builds have been reported to fail on the current implementation
when provided with negative values with:
  error: immediate must be an integer in range [0, 65535].

To resolve this, add a mask for the line filling the top 16 bits, like
the other lines already had.

Reported-by: Michael Kubacki <mikuback@linux.microsoft.com>
Signed-off-by: Leif Lindholm <leif.lindholm@oss.qualcomm.com>
(cherry picked from commit 3e7e3e2467445fe3b5931c1423a36df09cc26a80)