.pytool/Plugin/RustHostUnitTestPlugin: Ensure strings in ignore list
An ignore list is created in the plugin and passed as an argument to
`join()` in a couple places. For example:

- RustHostUnitTestPlugin.py:

  `logging.debug(f"Paths to ignore when computing coverage: {' '.join(ignore_list)}")`

- RustPackageHelper.py:

  `params += f' -e COV_FLAGS="--out {report_type} --exclude-files {",".join(ignore_list)}"'`

`join()` expects an iterable of strings. However, `Path` objects can
be added to the list. For example:

  `[pkg.path for pkg in rust_ws.members]`

(where `pkg.path` is a `Path` object)

This causes the following error:

```
   File ".pytool\Plugin\RustHostUnitTestPlugin\RustHostUnitTestPlugin.py", line 40, in RunBuildPlugin
    logging.debug(f"Paths to ignore when computing coverage: {' '.join(ignore_list)}")
                                                              ^^^^^^^^^^^^^^^^^^^^^
 TypeError: sequence item 1: expected str instance, WindowsPath found
 ```

This change converts all of the objects to their string representations
after `ignore_list` is finalized to simplify prior logic and ensure the
list consists of strings.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>